### PR TITLE
chore(build): add husky for git hooks

### PR DESCRIPTION
**Pull request by zewa666**
perform a lint before pushing changes to prevent unnecessary issues

### CODE REVIEW

**Comment by zewa666** [comment]
also updates the missing version bump for `package-lock.json` for v.0.2.1

**Comment by pjmolina** [comment]
Not sure if we should add the git hook to keep it DRY.
Ponder that CI in Travis already does lint + npm test for every Pull Request and we catch it before mergering.

**Comment by zewa666** [comment]
alright, didn't see the travis step. Nevertheless we should make sure the package-lock.json is properly updated

**Comment by pjmolina** [comment]
Agreed. 👍 
Closing this PR for the moment. If needed, we can incorporate it later.

**Pull request closed without merging**
