### PR TITLE
Extend pegjs grammar to allow specifying types

### PR DESCRIPTION
**Pull request by avishorp**
This PR includes a new parser that makes it possible to incorporate type information directly inside the grammar. It also improves the generated parser code, based on the specified types and a type inference system, to create a more type-safe code.

### CODE REVIEW

**Comment by pjmolina** [comment]
Hi @avishorp 
Testing your PR I get the following errors:
```
```

**Comment by pjmolina** [comment]
Hi @avishorp 
Testing your PR I found the following when launching `npm test`

```
> jest

 FAIL  test/unit/infer-types.spec.js
  ● Test suite failed to run

    Cannot find module 'pegjs' from 'infer-types.js'

      2 |
      3 | const uniq = require('lodash.uniq');
    > 4 | const visitor = require('pegjs').compiler.visitor;
        |                 ^
      5 | const { GrammarError } = require('pegjs');
      6 |
      7 | const __hasOwnProperty = Object.prototype.hasOwnProperty;

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.require (src/passes/infer-types.js:4:17)

 FAIL  test/unit/generate-bytecode-ts.spec.js
  ● Test suite failed to run

    Cannot find module 'pegjs/lib/compiler/asts' from 'generate-bytecode-ts.js'

      3 | // Base: (original file: generate-bycode.js for codegen JS)
      4 |
    > 5 | var asts = require("pegjs/lib/compiler/asts");
        |            ^
      6 | var js = require("pegjs/lib/compiler/js");
      7 | var op = require("pegjs/lib/compiler/opcodes");
      8 | var visitor = require("pegjs/lib/compiler/visitor");

      at Resolver.resolveModule (node_modules/jest-resolve/build/index.js:221:17)
      at Object.require (src/passes/generate-bytecode-ts.js:5:12)

 PASS  test/unit/parser.spec.js

Test Suites: 2 failed, 1 passed, 3 total
Tests:       62 passed, 62 total
Snapshots:   0 total
Time:        6.52s
Ran all test suites.
npm ERR! Test failed.  See above for more details.
```

**Comment by avishorp** [comment]
I actually abandoned this PR. I completely re-implemented a TS plugin for
PEG.js, based on the most recent (but unreleased) version. You can find the
source code at: https://gitlab.com/kihub.io/pegjs-ts-plugin (still WIP).

Avishay.

‫בתאריך יום ב׳, 27 במאי 2019 ב-14:56 מאת ‪Pedro J. Molina‬‏ <‪
notifications@github.com‬‏>:‬

**Comment by pjmolina** [comment]
OK. Thanks for your contribution @avishorp  and sorry for my late reply.
I will close this PR.

**Pull request closed without merging**
