### PR TITLE
fix src type

### PR DESCRIPTION
**Pull request by mo-ba**
in Webstorm/IntelliJ the missing type results in an error (although TSC works fine)

### CODE REVIEW

**Review by pjmolina — APPROVED** [review]
looks good to me

**Comment by insidewhy** [comment]
@pjmolina Could you publish a new release with this fix? The typecheck in our CI processes is failing due to this typing error.

**Comment by insidewhy** [comment]
@mo-ba `tsc` does not work when using the `--strict` option.

**Comment by pjmolina** [comment]
Sure! Published as v. 1.2.1.

**Comment by insidewhy** [comment]
@pjmolina Thanks!

**Pull request merged**
